enableGlobalCache: true

injectEnvironmentFiles:
  - .env

nodeLinker: node-modules

npmScopes:
  canopie-club:
    npmAuthToken: "${CANOPIE_GIT_PAT}"
    npmRegistryServer: "https://npm.pkg.github.com"
  tiptap-pro:
    npmAuthToken: "${TIPTAP_PRO_TOKEN}"
    npmRegistryServer: "https://registry.tiptap.dev/"

packageExtensions:
  "@tiptap-pro/extension-drag-handle@*":
    peerDependencies:
      "*": "*"
  "@tiptap-pro/extension-node-range@*":
    peerDependencies:
      "*": "*"
  y-prosemirror@*:
    peerDependencies:
      prosemirror-model: "*"
      prosemirror-state: "*"
      prosemirror-view: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
