nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs

enableGlobalCache: true

injectEnvironmentFiles:
  - .env

npmScopes:
  tiptap-pro:
    npmRegistryServer: "https://registry.tiptap.dev/"
    npmAuthToken: "${TIPTAP_PRO_TOKEN}"
  canopie-club:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${CANOPIE_GIT_PAT}"

packageExtensions:
  "@tiptap-pro/extension-drag-handle@*":
    peerDependencies:
      "*": "*"
  "@tiptap-pro/extension-node-range@*":
    peerDependencies:
      "*": "*"
